// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkvgyFkEC5IafbgOmvLRwWnO3xsgG4nZs',
    appId: '1:247288800844:web:56955f819ba453231576e9',
    messagingSenderId: '247288800844',
    projectId: 'mobileauthv2',
    authDomain: 'mobileauthv2.firebaseapp.com',
    databaseURL: 'https://mobileauthv2-default-rtdb.firebaseio.com',
    storageBucket: 'mobileauthv2.appspot.com',
    measurementId: 'G-L8PBEZTWMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzAC7XngyTqEcEuLn6ylCk8tg_LZqJ0_8',
    appId: '1:247288800844:android:97df21ff6b4dc7021576e9',
    messagingSenderId: '247288800844',
    projectId: 'mobileauthv2',
    databaseURL: 'https://mobileauthv2-default-rtdb.firebaseio.com',
    storageBucket: 'mobileauthv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDB97X6Rsu5e1JvdDrzIYSmfKfvtWhlXo',
    appId: '1:247288800844:ios:f26a0d3f20a5713c1576e9',
    messagingSenderId: '247288800844',
    projectId: 'mobileauthv2',
    databaseURL: 'https://mobileauthv2-default-rtdb.firebaseio.com',
    storageBucket: 'mobileauthv2.appspot.com',
    iosBundleId: 'com.example.kraapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDB97X6Rsu5e1JvdDrzIYSmfKfvtWhlXo',
    appId: '1:247288800844:ios:4108567c67b5145d1576e9',
    messagingSenderId: '247288800844',
    projectId: 'mobileauthv2',
    databaseURL: 'https://mobileauthv2-default-rtdb.firebaseio.com',
    storageBucket: 'mobileauthv2.appspot.com',
    iosBundleId: 'com.example.kraapp.RunnerTests',
  );
}
