// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkMDCzPjmU7S4pkHSNmcBZ4f-5uJsBi4',
    appId: '1:103055315510:web:13aa0a5bd095be56b63e97',
    messagingSenderId: '103055315510',
    projectId: 'fir-testingone-e3d83',
    authDomain: 'fir-testingone-e3d83.firebaseapp.com',
    databaseURL: 'https://fir-testingone-e3d83-default-rtdb.firebaseio.com',
    storageBucket: 'fir-testingone-e3d83.appspot.com',
    measurementId: 'G-SGGBE565C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCOP4X5-BLtSp7aWddJ6qfNno8HqkFCf8',
    appId: '1:103055315510:android:0f43b305b9160e6cb63e97',
    messagingSenderId: '103055315510',
    projectId: 'fir-testingone-e3d83',
    databaseURL: 'https://fir-testingone-e3d83-default-rtdb.firebaseio.com',
    storageBucket: 'fir-testingone-e3d83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMDjn_eeoORxFI0aoRT4MH1gZ8YI3EacI',
    appId: '1:103055315510:ios:7bf09ef0aba33e9db63e97',
    messagingSenderId: '103055315510',
    projectId: 'fir-testingone-e3d83',
    databaseURL: 'https://fir-testingone-e3d83-default-rtdb.firebaseio.com',
    storageBucket: 'fir-testingone-e3d83.appspot.com',
    iosBundleId: 'com.example.kraapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMDjn_eeoORxFI0aoRT4MH1gZ8YI3EacI',
    appId: '1:103055315510:ios:d06d7a242588a181b63e97',
    messagingSenderId: '103055315510',
    projectId: 'fir-testingone-e3d83',
    databaseURL: 'https://fir-testingone-e3d83-default-rtdb.firebaseio.com',
    storageBucket: 'fir-testingone-e3d83.appspot.com',
    iosBundleId: 'com.example.kraapp.RunnerTests',
  );
}
