// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxMj1T3o-ufX9GjdiwMQUjbkcWZSgT6i8',
    appId: '1:87513680665:web:4604b41b7b42c5bb1a1388',
    messagingSenderId: '87513680665',
    projectId: 'mobileauthv3-c6f14',
    authDomain: 'mobileauthv3-c6f14.firebaseapp.com',
    storageBucket: 'mobileauthv3-c6f14.appspot.com',
    measurementId: 'G-H8TWESFR01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnT2fq94P5oxAr6-mHcsx-cYq1-KkYsiQ',
    appId: '1:87513680665:android:d98b6ce2ade3e1621a1388',
    messagingSenderId: '87513680665',
    projectId: 'mobileauthv3-c6f14',
    storageBucket: 'mobileauthv3-c6f14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-xEV0xL9nlrEb0Zpw0qo5dsofJdDzUOI',
    appId: '1:87513680665:ios:cc29c90f92f31bab1a1388',
    messagingSenderId: '87513680665',
    projectId: 'mobileauthv3-c6f14',
    storageBucket: 'mobileauthv3-c6f14.appspot.com',
    iosBundleId: 'com.example.kraapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-xEV0xL9nlrEb0Zpw0qo5dsofJdDzUOI',
    appId: '1:87513680665:ios:1b2827bb24806e1a1a1388',
    messagingSenderId: '87513680665',
    projectId: 'mobileauthv3-c6f14',
    storageBucket: 'mobileauthv3-c6f14.appspot.com',
    iosBundleId: 'com.example.kraapp.RunnerTests',
  );
}
